-- 「這一句我錯在哪個文法點」。
--
-- 批改本來就會標文法點（`Correction.grammar_point`），而且那些標籤已經
-- 在驅動文法題的排程。缺的是**對回句子**：修正是整份練習的一張清單，
-- 說不出哪一條屬於哪一句。
--
-- 有了它，複習一個單字時看得到的不只是「我在這句用過它」，還有
-- 「我在這句上錯過冠詞」。反過來也成立：從文法點查得到踩過的句子。
--
-- 存識別碼（`articles`）而不是中文名稱：名稱在 `grammar_def` 裡，
-- 使用者可以改，存副本只會有兩份互相漂移的真相。
ALTER TABLE word_sentence ADD COLUMN grammar_points_json TEXT NOT NULL DEFAULT '[]';
